# ./build/src/app/get_semantics videos/segbot_v4_run.mkv data/trial0/map1/keyframe_trajectory.csv NA config/yolov5_best.onnx config/frozen_east_text_detection.pb third_party/tesseract/tessdata/ data/trial0/ > out0.out
./build/src/app/get_semantics videos/segbot_v4_run.mkv data/trials/trial1/map1/keyframe_trajectory.csv NA config/yolov5_best.onnx config/frozen_east_text_detection.pb third_party/tesseract/tessdata/ data/trial1/ > out1.out
# ./build/src/app/get_semantics videos/segbot_v4_run.mkv data/trials/trial2/map1/keyframe_trajectory.csv NA config/yolov5_best.onnx config/frozen_east_text_detection.pb third_party/tesseract/tessdata/ data/trial2/ > out2.out
# ./build/src/app/get_semantics videos/segbot_v4_run.mkv data/trials/trial3/map1/keyframe_trajectory.csv NA config/yolov5_best.onnx config/frozen_east_text_detection.pb third_party/tesseract/tessdata/ data/trial3/ > out3.out
# ./build/src/app/get_semantics videos/segbot_v4_run.mkv data/trials/trial4/map1/keyframe_trajectory.csv NA config/yolov5_best.onnx config/frozen_east_text_detection.pb third_party/tesseract/tessdata/ data/trial4/ > out4.out
# ./build/src/app/get_semantics /media/david/Extreme\ SSD/placard_discovery/videos/run4.mkv data/trials/trial5/map1/keyframe_trajectory.csv NA config/yolov5_best.onnx config/frozen_east_text_detection.pb third_party/tesseract/tessdata/ data/trial5/ > out5.out
# ./build/src/app/get_semantics /media/david/Extreme\ SSD/placard_discovery/videos/run4.mkv data/trials/trial6/map1/keyframe_trajectory.csv NA config/yolov5_best.onnx config/frozen_east_text_detection.pb third_party/tesseract/tessdata/ data/trial6/ > out6.out
# ./build/src/app/get_semantics /media/david/Extreme\ SSD/placard_discovery/videos/run4.mkv data/trials/trial7/map1/keyframe_trajectory.csv NA config/yolov5_best.onnx config/frozen_east_text_detection.pb third_party/tesseract/tessdata/ data/trial7/ > out7.out
# ./build/src/app/get_semantics /media/david/Extreme\ SSD/placard_discovery/videos/run4.mkv data/trials/trial8/map1/keyframe_trajectory.csv NA config/yolov5_best.onnx config/frozen_east_text_detection.pb third_party/tesseract/tessdata/ data/trial8/ > out8.out
# ./build/src/app/get_semantics /media/david/Extreme\ SSD/placard_discovery/videos/run4.mkv data/trials/trial9/map1/keyframe_trajectory.csv NA config/yolov5_best.onnx config/frozen_east_text_detection.pb third_party/tesseract/tessdata/ data/trial9/ > out9.out
# ./build/src/app/get_semantics /media/david/Extreme\ SSD/placard_discovery/videos/run4.mkv data/trials/trial10/map1/keyframe_trajectory.csv NA config/yolov5_best.onnx config/frozen_east_text_detection.pb third_party/tesseract/tessdata/ data/trial10/ > out10.out
# ./build/src/app/get_semantics /media/david/Extreme\ SSD/placard_discovery/videos/run4.mkv data/trials/trial11/map1/keyframe_trajectory.csv NA config/yolov5_best.onnx config/frozen_east_text_detection.pb third_party/tesseract/tessdata/ data/trial11/ > out11.out
# ./build/src/app/get_semantics /media/david/Extreme\ SSD/placard_discovery/videos/run4.mkv data/trials/trial12/map1/keyframe_trajectory.csv NA config/yolov5_best.onnx config/frozen_east_text_detection.pb third_party/tesseract/tessdata/ data/trial12/ > out12.out
